#!/bin/sh

CMD="$@"

if [ "$1" = "test" ]; then
   shift
   CMD="/app/ve/bin/py.test --flake8 $@"
fi

if [ "$1" = "coverage" ]; then
   shift
   CMD="/app/ve/bin/py.test --cov-report html --cov=$APP"
fi

if [ "$1" = "serve" ]; then
   shift
   CMD="/app/ve/bin/gunicorn -b 0.0.0.0:8000 -w 4 sms_auth_service.api:app $@"
fi

exec $CMD
